docs with Chinese
Portkey-AI/gateway pull request #159
Opened 2024-01-21 16:24 UTC by ye4293

**Title:** 
docs with Chinese

**Description:** (optional)
- add README.cn.md
- add CONTRIBUTING.cn.md

**Motivation:** (optional)
- make the project more widely disseminated

**Related Issues:** (optional)
- #issue-number

2024-01-27 07:27 UTC, roh26it requested changes
Thanks so much for the contribution! Docs in Chinese would really help with wider community!

Only 1 minor change which in my opinion wouldn't be needed in the English docs, otherwise this looks good to me.

2024-01-27 07:27 UTC, roh26it commented on .github/CODE_OF_CONDUCT.md
> +community a harassment-free experience for everyone, regardless of age, bodys
@ye4293 Hi, is this a necessary change?

2024-03-06 04:23 UTC, vrushankportkey requested changes

2024-03-06 04:23 UTC, vrushankportkey commented on .github/CODE_OF_CONDUCT.md
> +community a harassment-free experience for everyone, regardless of age, bodys
can we retain "body"

2024-04-10 08:18 UTC, vrushankportkey commented
addresses #296

2024-04-10 08:19 UTC, merged