📖 DOC: Install Run Deploy
Portkey-AI/gateway pull request #208
Opened 2024-02-15 07:59 UTC by saif-shines

The instructions are to install, run, and deploy the AI gateway in different channels.

- [ ] Show the channels to run and deploy the AI gateway on the README.md
- [ ] Clarify untold instructions like installing NodeJS or Importing the repository to Netlify or Replit using Hyperlinks.
- [ ] Update the code snippets to show syntax highlighting
- [x] Introduce a new file `install-run-deploy.md` that has same purpose as `installation-deployments.md` to keep them both until the content is well articulated. Once ready, we could ensure only one exists.
- [ ] Ensure all the instructions from existing `intallation-deployments.md` stay. Improve them. 
- [ ] Instructions for Replit
- [ ] Instructions for Netlify
- [ ] Instructions for Vercel
- [x] Instructions for Local — `bunx` and `npx`
- [ ] Instructions for others (work in progress) 
- [ ] A seperate "deploy-on-replit.md" file will act as landing page on Replit instead of the current README.md as [landing page](https://replit.com/@portkey/AI-Gateway?v=1#README.md)

2024-02-15 08:42 UTC, vrushankportkey reviewed
Are we removing the https://github.com/Portkey-AI/gateway/blob/main/docs/installation-deployments.md file?

2024-02-15 08:56 UTC, saif-shines commented
We will keep both the files. It is just a convenience to edit one independently without disturbing the original.

_Updated the description properly_

2024-04-10 05:29 UTC, vrushankportkey requested changes

2024-04-10 05:29 UTC, vrushankportkey commented on README.md
Since there are no changes on this file, can we remove it from this PR?

2024-04-10 05:29 UTC, vrushankportkey commented on docs/installation-deployments.md
Can we standardise the section headings?

2024-04-10 08:33 UTC, closed without merging

2024-04-10 08:35 UTC, saif-shines commented on docs/installation-deployments.md
I tried to address these comments and raise another PR #297 

Reason: This PR has become old and is not rebased with the main branch. Instead of working with merge conflicts, raised an seperate PR.