Fix: convert anthropic stop_reason to finish_reason
Portkey-AI/gateway pull request #363
Opened 2024-05-14 09:08 UTC by unsync

**Description:**
Currently, we forward the anthropic `stop_reason`, which is not compatible with the openai `finish_reason`.

This can cause warnings from some OpenAI sdk.

The conversion function returns `stop` as a default value in case new `stop_reason` are added.

2024-06-06 05:54 UTC, unsync commented
hello @vrushankportkey @VisargD, i'm not sure if there is a process after opening a PR to request a review, any chance this PR could be considered ?

2024-06-06 07:55 UTC, vrushankportkey commented
Thank you so much @unsync! Yes, we're checking the PR and will share review if any in some time! Really appreciate you pushing this bugfix 🙌

2024-07-17 08:02 UTC, narengogi commented on src/providers/anthropic/chatComplete.ts
> +const getFinishReason = (stopReason?: string): string | null => {
Recommend creating a type
```
type AnthropicStopReason = 'max_tokens' | 'stop_sequence' | 'end_turn' | ....
```

2024-07-17 08:04 UTC, narengogi commented on src/providers/anthropic/chatComplete.ts
> +  return 'stop';
This is okay, but not recommended, if we already know all the possible stop_reason supplied by anthropic, we should have a 1:1 mapping

2024-07-17 08:08 UTC, narengogi commented on src/providers/anthropic/chatComplete.ts
> +const getFinishReason = (stopReason?: string): string | null => {
also recommend using a switch/case

2024-07-17 08:09 UTC, narengogi commented on src/providers/anthropic/chatComplete.ts
> +            getFinishReason(response.stop_reason) || response.stop_reason,
This should just be `getFinishReason(response.stop_reason)`, Otherwise it defeats the purpose of strictly typing the response

2024-07-17 08:15 UTC, narengogi requested changes
Thanks for the Pull Request! Requested a few changes

2024-07-17 08:15 UTC, narengogi commented on src/providers/google/chatComplete.ts
> +const getFinishReason = (stopReason?: string): string | null => {
Same comments as in the getFinishReason transformer function above.
1. Use switch/case
2. Define types for GoogleStopReason

2024-07-17 08:15 UTC, narengogi commented on src/providers/google/chatComplete.ts
> +              getFinishReason(generation.finishReason) ??
should only be
```
finish_reason:
           getFinishReason(generation.finishReason) 
```
default case should be handled inside `getFinishReason`

2024-07-22 07:03 UTC, narengogi commented
@unsync I've created a fork of your branch to do some more thorough changes, it has your exisiting commits https://github.com/Portkey-AI/gateway/pull/468

2024-07-22 07:28 UTC, unsync commented
> @unsync I've created a fork of your branch to do some more thorough changes, it has your exisiting commits #468

@narengogi that is great !
I think your PR is a better candidate for merge than mine, i think my PR can be close in favour of yours ?

cc @vrushankportkey

2024-07-22 07:38 UTC, vrushankportkey commented
Thanks @unsync & @narengogi!

2024-07-22 07:53 UTC, closed without merging