update cohere endpoints & response template
Portkey-AI/gateway pull request #415
Opened 2024-06-28 05:53 UTC by b4s36t4

**Title: Depreciate /generate endpoint for cohere provider** 
- Updates cohere endpoints in favour of depreciating  generate endpoint.

**Motivation:** (optional)
- Why this change is necessary or beneficial

**Related Issues:** (optional)
/closes #321

2024-06-28 06:00 UTC, VisargD commented on src/providers/cohere/complete.ts
Hey. This is the complete handler so users would still be expected to send prompt instead of messages. I would suggest that we either ask for prompt and convert to messages with a transformer. Or else we can keep it same as the existing implementation and use /generate endpoint until cohere releases a final deprecation notice.

2024-07-26 10:39 UTC, narengogi requested changes
I've checked out your branch and ran a test, but it fails.
Please find attached relevant curl request
```
curl --location 'http://localhost:8787/v1/chat/completions' \
--header 'x-portkey-provider: cohere' \
--header 'Authorization: $COHERE_API_KEY' \
--header 'Content-Type: application/json' \
--data '{
    "model": "command-r-plus",
    "max_tokens": 200,
    "stream": false,
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant"
    },
          {
        "role": "user",
        "content": "Hello Alfred, how are you?"
    }
    ]
}'
```

2024-07-26 10:45 UTC, narengogi commented on src/providers/cohere/chatComplete.ts
> +            message: message.content as string,
also need to handle messages of object type
```
            {
        "role": "assistant",
        "content": [
          {
            "type": "text",
            "text": "is it me?"
          }
        ]
      }
```
You can refer https://platform.openai.com/docs/api-reference/chat/create for openai request structure.
Gateway transforms requests from OpenAI format to provider specific format, so all the possible request variations from. openai need to be handled by the gateway transformer

2024-08-28 14:40 UTC, VisargD commented on package-lock.json
Can we remove this file from PR if its not required? I don't see any package.json changes

2024-08-29 13:56 UTC, VisargD approved these changes

2024-08-29 13:56 UTC, merged