Feat: Provider Tests
Portkey-AI/gateway pull request #494
Opened 2024-08-02 12:53 UTC by narengogi

**Title:** 
- Tests for providers to make sure they are OpenAI compliant

Initial idea for this sprung from reading the very descriptive GitHub issue raised by @raulraja https://github.com/Portkey-AI/gateway/issues/116

**Motivation:** (optional)
- Multiple provider's transformers are not OpenAI spec compliant, they fail to transform cases like user message content array
```
    {
      role: 'user',
      content: [
        {
          type: 'text',
          text: 'Who is the greatest detective',
        },
      ],
    }
```
- Already caught 6 transformers failing from 12 I tested for the two test cases.

**Related Issues:** (optional)
- #116

**TO-DO:**
- [ ] Push config file
- [ ] Add flag to test only specific providers
- [ ] GitHub actions

2024-08-02 12:54 UTC, narengogi commented
For your review @VisargD  @sk-portkey

2024-08-12 05:58 UTC, sk-portkey commented on src/tests/resources/providersConfig.ts
> +const providersConfig: Record<keyof typeof Providers, any> = {
Lets strictly define type here.
ProviderTestConfig
Type ProviderTestConfig
name : keyof typeof Providers,
provider/ApiKey,
operations: LlmOperation (defined below)
skip?: boolean (if they want to skip this call)

type LlmOperation
type: 'completions' | 'chatCompletions' | 'proxy'
operation: object

2024-08-12 06:00 UTC, sk-portkey commented on src/tests/chatCompletions.test.ts
> +for (const provider in providersConfig) {
Instead of operation level, we can go by Provider Level. As we are aware of what each provider supports.

2024-08-12 06:01 UTC, sk-portkey commented on src/tests/resources/constants.ts
> +const baseURL = 'http://localhost';
provide an option to fetch the details from env

2024-08-12 07:24 UTC, sk-portkey requested changes
move from feature specific to provider level testing

2024-08-13 10:02 UTC, sk-portkey submitted a review, later dismissed

2024-08-13 10:03 UTC, sk-portkey commented
@narengogi can you update to main. else lgtm

2024-08-22 09:58 UTC, merged