fix: siliconflow error response
Portkey-AI/gateway pull request #636
Opened 2024-09-29 13:04 UTC by sternelee

2024-10-01 13:55 UTC, VisargD approved these changes, later dismissed

2024-10-01 13:56 UTC, VisargD commented
Hey! Will it be possible to add the documentation link in the PR description to point out why this is required? It will make it easy to track things in future. Thanks!

2024-10-24 12:48 UTC, narengogi commented on src/providers/deepbricks/api.ts
> +  getBaseURL: () => 'https://api.deepbricks.ai',
any reason for this?

2024-10-24 13:18 UTC, narengogi requested changes

2024-10-24 13:18 UTC, narengogi commented on src/providers/siliconflow/chatComplete.ts
> +  return response as ChatCompletionResponse;
would recommend changing the structure of this function to 
```
if ('contents' in response) {
 return response
 }
 if (responseStatus !== 200 && typeof response === 'string') {
    return SiliconFlowErrorResponseTransform(
      { message: response, code: String(responseStatus) },
      SILICONFLOW
    );
  }
  else return generateInvalidProviderResponseError(response, SILICONFLOW)
```

2024-10-24 13:18 UTC, narengogi commented on src/providers/siliconflow/chatComplete.ts
> +  return response as ChatCompletionResponse;
Same comment for other updated functions as well

2024-12-26 10:18 UTC, VisargD commented
Moving this PR to draft state. Please make it ready for review one the comment is addressed. https://github.com/Portkey-AI/gateway/pull/636#discussion_r1814976254

2025-01-13 08:41 UTC, VisargD commented
Closing this PR due to inactivity. Please feel free to reopen whenever required. Thanks!

2025-01-13 08:41 UTC, closed without merging