lowercase-plugin
Portkey-AI/gateway pull request #648
Opened 2024-10-02 11:36 UTC by thev19

**Lowercase-plugin** 
- Added a plugin to check if the given string is lowercase or not.

**Related Issues:** 
- #514

2024-10-03 08:13 UTC, b4s36t4 commented
@thev19 PR seems to be having some conflicts, can you resolve them first?

2024-10-03 10:45 UTC, thev19 commented
@b4s36t4 Resolved the merge conflicts.

2024-10-03 12:39 UTC, b4s36t4 requested changes

2024-10-03 12:39 UTC, b4s36t4 commented on plugins/default/manifest.json
> +    }
This seems to be conflict issue, can you fix this?

2024-10-03 12:39 UTC, b4s36t4 commented on plugins/default/default.test.ts
> +describe('allLowercase handler', () => {
Test cases are only added for `afterRequestHook`. Can we please add the same for `beforeRequestHook` as well please?

2024-10-13 17:37 UTC, thev19 commented on plugins/default/default.test.ts
> +describe('allLowercase handler', () => {
added beforeRequestHook.

2024-10-14 07:49 UTC, b4s36t4 approved these changes

2024-10-18 11:23 UTC, merged