added valid number range
Portkey-AI/gateway pull request #679
Opened 2024-10-14 15:43 UTC by nikhil-kumar94

**Title:** 
- Valid Number range plugin

**Related Issues:**
- #674

2024-10-15 04:48 UTC, b4s36t4 requested changes

2024-10-15 04:48 UTC, b4s36t4 commented on plugins/default/validNumberRange.ts
> +  upperLimit: Number
`Number` isn't a type. use `number` instead.

2024-10-15 04:48 UTC, b4s36t4 commented on plugins/default/validNumberRange.ts
> +}
I don't think this logic is what the expectation is. Ideally plugins are used as part of generation so we must be able to use this rule with generated content. This rule must check weather the generated content (number) is within the range.

use `getText` function to retrieve the message content and make sure the content is number (or possibly use regex to extract number from the message content) and do validation with the extracted number.

Check existing plugins here: https://github.com/Portkey-AI/gateway/tree/main/plugins/default

2024-11-08 15:18 UTC, VisargD commented
Hey @nikhil-kumar94 and @b4s36t4 , is there any blocker for this PR? Please let me know if you have any doubts.

2024-11-26 07:54 UTC, VisargD commented
Closing this PR due to inactivity. Please feel free to reopen it whenever required

2024-11-26 07:54 UTC, closed without merging