docs : Update installation-deployments.md
Portkey-AI/gateway pull request #706
Opened 2024-10-24 00:50 UTC by Akshay-66

**Documentation : Update installation-deployments.md**

Added steps of deployment for
- Vercel
- Fastly
- AWS Lambda
- Lambda@edge
- Supabase Functions

**Motivation:** 
- Enhances ease for users (devs).

2024-10-24 12:12 UTC, narengogi requested changes
Please only add steps for environments in which you have personally deployed and tested

2024-10-24 12:12 UTC, narengogi commented on docs/installation-deployments.md
> +2. Prepare the project for Lambda@Edge deployment by ensuring that request handling works within CloudFront constraints.
what does this mean? have you deployed this on AWS lambda and tested? Please don't publish AI generated docs

2024-10-24 14:20 UTC, Akshay-66 commented on docs/installation-deployments.md
> +2. Prepare the project for Lambda@Edge deployment by ensuring that request handling works within CloudFront constraints.
Oh, Sorry for that i've refered official site but don't know i have to deploy myself.
- I’ll make sure to validate the process before publishing the docs. I’ll update this once the steps are verified.

Thank you @narengogi

2024-10-25 17:44 UTC, Akshay-66 commented
Deployed and tested portkey on
   - Supabase Function
   - Fastly
   
And added steps of deployment for the same.
![Screenshot 2024-10-25 214031](https://github.com/user-attachments/assets/6e7ed1dd-eb62-4a3c-b89d-475541d572d0)
![Screenshot 2024-10-25 214402](https://github.com/user-attachments/assets/6530bfd7-035d-493a-886a-60a84e6afb36)
![Screenshot 2024-10-25 062222](https://github.com/user-attachments/assets/a35d7c03-de1c-4a62-a081-160408e4b657)
![Screenshot 2024-10-25 062254](https://github.com/user-attachments/assets/0290c061-afb4-4c9e-bdae-587bba35c8e2)

2025-01-17 08:16 UTC, narengogi approved these changes

2025-06-25 08:17 UTC, VisargD commented
Hey @Akshay-66 , @siddharthsambharia-portkey has raised another PR from this one which resolves the merge conflicts. Your original commits are preserved in the new PR #1170 

Closing this one in favour of the new PR. Thanks!

2025-06-25 08:17 UTC, closed without merging